{
  imports = [
    ./gather.nix
    ./common/default.nix
    ./boot/default.nix
    ./server.nix
    ./serial.nix
    ./peering/default.nix
    ./backup.nix
    ./platform/default.nix
    ./letsencrypt.nix
    ./web
    ./firewall.nix
    ./docker.nix
    ./builder.nix
    ./hive/default.nix
    ./dns/host.nix
    ./network.nix
    ./ipam.nix
    ./monitoring/default.nix
  ];
}
