{
	"data": "ENC[AES256_GCM,data:2lRPVMdJajoP0oOA8Tlsz7B6cmRizHW4ybkyXeLNkS05PwGVFAkOATSwm/eL1FNgEmPC16Zf4x+UrmZ9yItZNR7k0LSEwLAcpGnLhA2HHGDCyktSPxhpBUM0eG+diiiKMLk1RkIdKgcYEjqBiqs8qxy54JhWzZJNXWFpf0WR4my8FN0PeTtattdYgAkF85HIsSzgpzt4k6RgjrgHE8xDXUH59kWbx7pU1+J/DvoYX3v/hs/3wol0K6jaHgCxHi8uzu9SOSCamKQ+ieIYkD3OaEUy5Std/tIUjdrdmcdyUbPOMG/FZU3xD/M4LTBF2nhT7fsa/6gKWBV/Yvrz72f8JZjMnE+816MhDjEH5fY/CGFew5uRJheWidi4/KKQq8k1PVGg0gQgXqQJ8KEL0zxpyc+Lf/2ubToiLy2YxmbWs2nOHSR4FvD1oerSc4M1s+3WqqsAjjQje9bgnIc=,iv:CClK4VEDHezfhM8CWAQWDmo145mpr25s6HkLWjujHcc=,tag:LDkvLOdEtnfwu3W7xyBObA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age13eqz4wf4729njr3pv8xevfnecfk8cq8tzk4qpee6las09j3423eskjjfsz",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVENqWjZXZUdTYmVGN2NL\nNzBzN2RVSGdNbDhmR0YxV0pvWUUxK0pkYlhjCmllTHBuSXhOUDBRdkxzTXpHZWdq\nNnJtWWwyWndTSTdZZFFrV0xtUjBVNkkKLS0tIE1VTFVnQ09mVFVVcHJVc21hdnpQ\nNFVZRVBvNDhjZ0VpT2JkM2d6dWpRNjgKdLZGaPw6j9pcD6yFm73BXp/eNRLGCscw\nSACDHqfY2ZTnWegNPDZXYyI30K5z22bajdn9ZhVGcOZ/7iXHNHXJnA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-06-13T11:21:42Z",
		"mac": "ENC[AES256_GCM,data:Q+FGDVmdjoO2ucH9vSXP/uiJvccHitkXExf+mKihuoAp8GjAZ/LNaWLe6ZBo0z77Qld6gJ8RsI51wZD/NN+xG/r8UdJdwb1S9VO6ywnbvPAnsaBYTVKvPPr/R351CDB5Stwd9txvcQQmnIz1DS9nK2FGIniucssF7OYq5uHlzw0=,iv:Qnaudn+vImu6pdCjDNzuYlUpxUennSLUDeq7eDDUHO4=,tag:TWp4pUkDQP5qJabm5WcqeQ==,type:str]",
		"pgp": [
			{
				"created_at": "2023-06-13T07:52:22Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQEMA5ntoryXZPD4AQf/VBlDpmbqqPDzDoWZXJq/xQ0VQXqyJchwaEwyF2GIEylc\n9RZ+0iRmaViVZSNVsPT8RBTULrVWp92djqLGGz8s2LpaikM5T99apMHJefUyDJ22\n8EXHXzsWqS3OfpgfEa/WW0yowskvAn6tuQWYuRcgkqXU0y7QqjMqKvgFYxuSrYNB\nKRVwtKoZApEgkLsEp3itEyz98kmWtScO4PWEpslBJu/dG9vhwnk/8qEcyJHst0qj\nfROTdv07f2/bvmSso42zaEMw2c8cLEpsMrk/McJ9qzQq5mfM3VdqG10iK/koaP/m\nJRdnck4HILnq4OjAP/nTeHahdKbSQMl82lTydvM33dJeAXRsdyG/9ubKlClIpRU2\nXXreAGVtIyhdC28WGVbTbxYdxuw6d/h/q12DBZwX5lXp2d8ayB5+J5EWBaG5UqAc\ngrIsVyGvzLemRPC3yVLWuNRmcGulKndHgmB9T4lXFw==\n=GU06\n-----END PGP MESSAGE-----\n",
				"fp": "3237CA7A1744B4DCE96B409FB4C3BF012D9B26BE"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}