#!/usr/bin/env bash

set -euo pipefail

declare -a MACHINES
if [[ "${1}" != "" ]]; then
	MACHINES=( "${1}" )
else
	mapfile -t MACHINES < <(cd machines && find . -name 'machine.nix' -printf '%P\0' | xargs -0 dirname)
fi

for MACHINE in "${MACHINES[@]}"; do
	echo "-- ${MACHINE} --"
	MACHINE_DIR="$(pwd)/machines/${MACHINE}"
	
	TARGET="$(nix eval --raw --impure --expr "(with import \"${MACHINE_DIR}/machine.nix\"; \"\${target.user}@\${target.host}\")")"
	echo "Target: ${TARGET}"

	mkdir -p "${MACHINE_DIR}/gathered"

	ssh "${TARGET}" "/run/gather" | tar xv --dereference --directory "${MACHINE_DIR}/gathered"
	
done
